version: 2

updates:
    -   package-ecosystem: "composer"
        directory: "/tools"
        schedule:
            interval: "weekly"
        groups:
            tools:
                patterns: [ "*" ]

    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "weekly"
        groups:
            symfony:
                patterns: [ "symfony/*" ]
