name: "Tests"

on:
    pull_request: ~
    push:
        branches: [ main ]

permissions:
    contents: read

jobs:
    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v4

            -   name: "Setup PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v3
                with:
                    composer-options: --optimize-autoloader

            -   name: "Run tests"
                run: composer tests -- --colors=always

    infection:
        name: Infection
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v4

            -   name: "Setup PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3

            -   name: "Install dependencies"
                uses: ramsey/composer-install@v3
                with:
                    composer-options: --optimize-autoloader

            -   name: "Run mutation tests"
                run: composer infection
                env:
                    INFECTION_DASHBOARD_API_KEY: ${{ secrets.INFECTION_DASHBOARD_API_KEY }}
