name: "Tests"

on:
    pull_request: ~
    push:
        branches: [ main ]

permissions:
    contents: read

jobs:
    phpunit:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3

            -   uses: ramsey/composer-install@v3
                with:
                    composer-options: --optimize-autoloader

            -   run: composer tests
